### ISSUE TITLE
`spnpipe-nf/SPN_Reference_DB/SPN-Primers2Trim.fasta` is missing from the repository

### ISSUE THREAD

**Issue by HarryHung** [CDCgov/spnpipe-nf#4]
**Describe the bug**
`spnpipe-nf/SPN_Reference_DB/SPN-Primers2Trim.fasta` is missing from the repository
It leads to error when executing `trim_reads` process

```
 cutadapt: error: [Errno 2] No such file or directory: 'spnpipe-nf/SPN_Reference_DB/SPN-Primers2Trim.fasta'
```

**Impact**
Fatal error of the pipeline

**To Reproduce**
Run the pipeline with a newly cloned repository

**Expected behavior**
`spnpipe-nf/SPN_Reference_DB/SPN-Primers2Trim.fasta` to be included

**Comment by glev-doug** [comment]
Added `SPN_Reference_DB/SPN-Primer2Trim.fasta` to branch, and merged changes to master.
